--USE [dclubar_crown]
--GO

/****** Object:  Table [mgr].[MA_STATSCHE]    Script Date: 09/14/2021 16:00:50 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [mgr].[MA_STATSCHE_DEFAULTER](
	[MEMBER_ID] [varchar](10) NOT NULL,
	[CONV_DATE] [datetime] NOT NULL,
	[OLD_STATUS] [varchar](4) NOT NULL,
	[NEW_STATUS] [varchar](4) NOT NULL,
	[REASON_CD] [varchar](4) NOT NULL,
	[REMARKS] [dbo].[T_DESCS] NULL,
	[SEND_ARTICLE] [char](1) NOT NULL,
	[RETURN_CARD] [char](1) NOT NULL,
	[MAIL_FLAG] [char](1) NULL,
	[ADDRESS1] [char](60) NULL,
	[ADDRESS2] [char](60) NULL,
	[ADDRESS3] [char](60) NULL,
	[POST_CD] [varchar](10) NULL,
	[ABS_END] [datetime] NULL,
	[OLD_MAIL_FLAG] [char](1) NULL,
	[OLD_ADDRESS1] [varchar](60) NULL,
	[OLD_ADDRESS2] [varchar](60) NULL,
	[OLD_ADDRESS3] [varchar](60) NULL,
	[OLD_POST_CD] [varchar](10) NULL,
	[STATUS] [char](1) NOT NULL,
	[AUDIT_USER] [dbo].[T_AUDIT_USER] NOT NULL,
	[AUDIT_DATE] [dbo].[T_AUDIT_DATE] NOT NULL,
	[AUTO_REVERSE] [char](1) NULL,
	[AUTO_CONVERT] [char](1) NULL,
	[PREV_STATUS] [varchar](4) NULL,
	[PREV_ABS_END] [datetime] NULL,
 CONSTRAINT [pk_ma_statsche_DEFAULTER] PRIMARY KEY CLUSTERED 
(
	[MEMBER_ID] ASC,
	[CONV_DATE] ASC,
	[OLD_STATUS] ASC,
	[NEW_STATUS] ASC,
	[AUDIT_DATE] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [mgr].[MA_STATSCHE_DEFAULTER]  WITH CHECK ADD  CONSTRAINT [FK_MA_STATSCHE_DEFAULTER_2__24] FOREIGN KEY([REASON_CD])
REFERENCES [mgr].[cf_reason] ([reason_cd])
GO

ALTER TABLE [mgr].[MA_STATSCHE_DEFAULTER] CHECK CONSTRAINT [FK_MA_STATSCHE_DEFAULTER_2__24]
GO


