--GOTO TABLE ROOMINFO > KEYS : DELETE PK_roominfo_roomtype
--THEN GOTO TABLE ROOMTYPE > COLUMN : DELETE ID, THEN CHECK KEYS : IF PK__roomtype__{randomID} DELETED, IF NOT GO DELETE IT.


--BEFORE YOU IMPORT THE DATA FROM THE SYSTEM. RUN THIS.
ALTER TABLE [dbo].[roomtype]
ADD ID INT;

--ONCE DONE IMPORTING. RUN THIS.
ALTER TABLE [dbo].[roomtype]
ALTER COLUMN ID INT NOT NULL;
ALTER TABLE [dbo].[roomtype]
ADD CONSTRAINT PK__roomtype__/*{EDIT THIS PART WITH THE NEW ID}*/ PRIMARY KEY (ID);

--ON ROOMTYPE PK__roomtype__3214EC2735EA8CCA -- LOOK THE UNDER TABLE ROOMTYPE > KEYS
--ON ROOMINFO PK_roominfo_roomtype

--THEN RUN THIS FINAL SCRIPT
ALTER TABLE [dbo].[roominfo]
ADD CONSTRAINT PK_roominfo_roomtype
FOREIGN KEY (roomtype)
REFERENCES [dbo].[roomtype](ID);