USE dclubv3_cuvc_live

SELECT
	C.DEBTOR_ACCT AS 'PRINCIPAL ID',
	D.MEMBER_ID AS 'DEPENDENT/NOMINEE ID',
	C.SEQ_NO AS 'SEQ. NO.',
	A.NAME AS 'PRINCIPAL NAME',
	D.NAME_ON_CARD AS 'DEPENDENT/NOMINEE NAME',
	A.BUSINESS_ID AS 'BUSINESS ID',
	C.STATUS_CD AS 'STATUS CODE',
	CASE
		WHEN C.STATUS_CD = 'A' THEN 'ACTIVE'
		WHEN C.STATUS_CD = 'D' THEN 'DEFAULTER'
		WHEN C.STATUS_CD = 'F' THEN 'FREEZE'
		WHEN C.STATUS_CD = 'H' THEN 'HONORARY'
		WHEN C.STATUS_CD = 'R' THEN 'TRANSFERRED'
		WHEN C.STATUS_CD = 'S' THEN 'SUSPEND / DISQUALIFY DEPENDENTS'
		WHEN C.STATUS_CD = 'T' THEN 'TERMINATED'
		WHEN C.STATUS_CD = 'X' THEN 'DECEASED'
		ELSE NULL
	END AS 'STATUS DESC.',
	C.MSHIP_TYPE AS 'TYPE CODE',
	CASE
		WHEN C.MSHIP_TYPE = 'I' THEN 'INDIVIDUAL'
		WHEN C.MSHIP_TYPE = 'C' THEN 'CORPORATE'
		ELSE 'LICENSEE'
	END AS 'MEMBERSHIP TYPE',
	C.CATEGORY_CD AS 'CATEGORY CODE',
	CASE
		WHEN C.CATEGORY_CD = 'TP8' THEN 'TRIAL PACK 8 YEARS'
		WHEN C.CATEGORY_CD = 'TP15' THEN 'TRIAL PACK 15 YEARS'
		WHEN C.CATEGORY_CD = 'TP25' THEN 'TRIAL PACK 25 YEARS'
		ELSE NULL
	END AS 'CATEGORY DESC.'
FROM
	mgr.CF_BUSINESS A,
	mgr.CF_BUSINESS B,
	mgr.MA_MSHIP C,
	mgr.MA_MEMBER D,
	mgr.AR_DEBTOR E
WHERE
	(A.COMPANY_SEQ_NO *= B.SEQ_NO) AND
	(C.MSHIP_ID = D.MSHIP_ID) AND
	(C.SEQ_NO = A.SEQ_NO) AND
	(C.DEBTOR_ACCT = E.DEBTOR_ACCT)
ORDER BY [PRINCIPAL ID]
GO
SELECT * FROM mgr.MAS_CATEGORY